---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
  # - name: centos-7.2

suites:
  - name: default
    driver:
      customize:
        memory: 8192
        cpus: 4
    run_list:
      - recipe[saasquatch::env_setup]
      - recipe[saasquatch::install_geoip]
      - recipe[saasquatch::default]
    attributes:
